name: test

on:
  push:
    branches: [main]
    paths: ['.github/workflows/test.yml']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actions funcionando OK"
